### ISSUE TITLE
[Issue]: NodeLabeler doesn't work for MI300X VF

### ISSUE THREAD

**Issue by xiongzubiao** [ROCm/gpu-operator#183]
### Problem Description

The GPU Driver is preinstalled. After installing the latest gpu-operator v1.2.1, the nodes have label `feature.node.kubernetes.io/amd-vgpu: "true"`, but no label `feature.node.kubernetes.io/amd-gpu`. Then I follow the instruction to add `DeviceConfig`, with one change: node selector is set to the `amd-vgpu` label because there is no `amd-gpu` label. I can see the node-labeler pods starting up, but there are no amd labels added to the nodes.

### Operating System

22.04.5 LTS (Jammy Jellyfish)

### CPU

Intel(R) Xeon(R) Platinum 8470

### GPU

AMD Instinct MI300X VF

### ROCm Version

6.4.0

**Comment by yansun1996** [comment]
Hi @xiongzubiao thanks for trying AMD GPU Operator

1. ```amd-vpu```: we are distinguishing the AMD GPU VF device from the PF device so that in your system with MI300X VF it shows the vgpu label.
2. You mentioned that driver is pre-installed, can you confirm by checking these in your VM worker node ? 
* Output of ```lsmod | grep amdgpu``` on your worker node
* Output of ```ls /dev/dri```
* Check driver version ```cat /sys/module/amdgpu/version```
* If lsmod shows the amdgpu module but card and render didn't appear in ```/dev/dri```, running ```dmesg``` will show the possible error
3. You mentioned that node labeller pod was brought up, can you show me the pod status ? 
* ```kubectl get pod <node labeller pod name> -n kube-amd-gpu -oyaml```
* ```kubectl logs <node labeller pod name> -n kube-amd-gpu```
4. It will be also helpful to see the node label from ```kubectl get node <your worker node name> -oyaml | grep amd.com```

**Comment by xiongzubiao** [comment]
@yansun1996 I think the driver and the node-labeler are actually working fine. I have tried manually adding `feature.node.kubernetes.io/amd-gpu: "true"` to the node and restarting the node-labeler pod, then the amd labels showed up. I found some code in the gpu-operator code that seems cleaning up amd labels if there is no `feature.node.kubernetes.io/amd-gpu` labels:
https://github.com/ROCm/gpu-operator/blob/dd3c2687d961763ac25f731f1451ccae231f4f69/internal/controllers/device_config_reconciler.go#L1065

Would that be the problem?

I think collect those information if you still think it is relevant.

**Comment by xiongzubiao** [comment]
> * Output of `lsmod | grep amdgpu` on your worker node

```
$ lsmod | grep amdgpu
amdgpu              17424384  4
amddrm_ttm_helper      16384  1 amdgpu
amdttm                 94208  2 amdgpu,amddrm_ttm_helper
amdxcp                 16384  1 amdgpu
amddrm_buddy           20480  1 amdgpu
amd_sched              53248  1 amdgpu
amdkcl                 45056  3 amd_sched,amdttm,amdgpu
i2c_algo_bit           16384  1 amdgpu
drm_kms_helper        311296  2 amdgpu,amdkcl
cec                    65536  2 drm_kms_helper,amdgpu
drm                   622592  10 drm_kms_helper,amd_sched,amdttm,amdgpu,amddrm_buddy,amdkcl,amddrm_ttm_helper,amdxcp
```

> * Output of `ls /dev/dri`

```
$ ls /dev/dri
by-path  card0  card1  card2  card3  card4  card5  card6  card7  renderD128  renderD129  renderD130  renderD131  renderD132  renderD133  renderD134  renderD135
```

> * Check driver version `cat /sys/module/amdgpu/version` 

```
$ cat /sys/module/amdgpu/version
6.12.12
```

> 3. You mentioned that node labeller pod was brought up, can you show me the pod status ?
> * `kubectl get pod <node labeller pod name> -n kube-amd-gpu -oyaml`

```
$ kubectl -n amd get pod -o yaml test-deviceconfig-node-labeller-wjtts
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-05-08T18:14:01Z"
  generateName: test-deviceconfig-node-labeller-
  labels:
    controller-revision-hash: 569fd66554
    daemonset-name: test-deviceconfig
    pod-template-generation: "1"
  name: test-deviceconfig-node-labeller-wjtts
  namespace: amd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: test-deviceconfig-node-labeller
    uid: 0c3037aa-9236-4538-b214-30a89e5b86a1
  resourceVersion: "1356"
  uid: 72cd9a32-6f46-4384-aef7-bde1f347c4a1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - enc1-gpuvm015
  containers:
  - args:
    - -c
    - ./k8s-node-labeller -vram -cu-count -simd-count -device-id -family -product-name
      -driver-version
    command:
    - sh
    env:
    - name: DS_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: rocm/k8s-device-plugin:labeller-latest
    imagePullPolicy: IfNotPresent
    name: node-labeller-container
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev
      name: dev-volume
    - mountPath: /sys
      name: sys-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jwbf9
      readOnly: true
    workingDir: /root
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sh
    - -c
    - rm -f /host-etc/modprobe.d/blacklist-amdgpu.conf; while [ ! -d /host-sys/class/kfd
      ] || [ ! -d /host-sys/module/amdgpu/drivers/ ]; do echo "amdgpu driver is not
      loaded "; sleep 2 ;done
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    name: driver-init
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host-sys
      name: sys-volume
    - mountPath: /host-etc
      name: etc-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jwbf9
      readOnly: true
  nodeName: enc1-gpuvm015
  nodeSelector:
    feature.node.kubernetes.io/amd-vgpu: "true"
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: amd-gpu-operator-node-labeller
  serviceAccountName: amd-gpu-operator-node-labeller
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - hostPath:
      path: /dev
      type: Directory
    name: dev-volume
  - hostPath:
      path: /sys
      type: Directory
    name: sys-volume
  - hostPath:
      path: /etc
      type: Directory
    name: etc-volume
  - name: kube-api-access-jwbf9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-05-08T18:14:02Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-05-08T18:14:02Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-05-08T18:14:04Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-05-08T18:14:04Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-05-08T18:14:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d93acbd4d024306a603bce74050cf34af825098fab183f18de32626dce748979
    image: docker.io/rocm/k8s-device-plugin:labeller-latest
    imageID: docker.io/rocm/k8s-device-plugin@sha256:c6040547109eae478e3f64c0cea8c0913f993717be8fd79b0e76c167f2bd4e78
    lastState: {}
    name: node-labeller-container
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-05-08T18:14:04Z"
    volumeMounts:
    - mountPath: /dev
      name: dev-volume
    - mountPath: /sys
      name: sys-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jwbf9
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 23.183.40.80
  hostIPs:
  - ip: 23.183.40.80
  initContainerStatuses:
  - containerID: containerd://47f48f8c4b14bb842b73e64c9154a2c4183f91dae174e37cbc56d48558c32a49
    image: docker.io/library/busybox:1.36
    imageID: docker.io/library/busybox@sha256:e246aa22ad2cbdfbd19e2a6ca2b275e26245a21920e2b2d0666324cee3f15549
    lastState: {}
    name: driver-init
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://47f48f8c4b14bb842b73e64c9154a2c4183f91dae174e37cbc56d48558c32a49
        exitCode: 0
        finishedAt: "2025-05-08T18:14:02Z"
        reason: Completed
        startedAt: "2025-05-08T18:14:02Z"
    volumeMounts:
    - mountPath: /host-sys
      name: sys-volume
    - mountPath: /host-etc
      name: etc-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jwbf9
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Running
  podIP: 10.42.0.20
  podIPs:
  - ip: 10.42.0.20
  qosClass: BestEffort
  startTime: "2025-05-08T18:14:01Z"
```

> * `kubectl logs <node labeller pod name> -n kube-amd-gpu`

```
$ kubectl -n amd logs test-deviceconfig-node-labeller-wjtts
Defaulted container "node-labeller-container" out of: node-labeller-container, driver-init (init)
{"level":"info","ts":"2025-05-08T18:14:04Z","logger":"amdgpu-node-labeller.entrypoint","msg":"setting up manager"}
{"level":"info","ts":"2025-05-08T18:14:04Z","logger":"amdgpu-node-labeller.entrypoint","msg":"Setting up controller"}
{"level":"error","ts":"2025-05-08T18:14:04Z","logger":"amdgpu-node-labeller","msg":"/sys/class/drm/card0/device/product_name","error":"open /sys/class/drm/card0/device/product_name: no such file or directory","stacktrace":"main.init.func6\n\t/go/src/github.com/ROCm/k8s-device-plugin/cmd/k8s-node-labeller/main.go:217\nmain.generateLabels\n\t/go/src/github.com/ROCm/k8s-device-plugin/cmd/k8s-node-labeller/main.go:384\nmain.main\n\t/go/src/github.com/ROCm/k8s-device-plugin/cmd/k8s-node-labeller/main.go:424\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
{"level":"info","ts":"2025-05-08T18:14:04Z","logger":"amdgpu-node-labeller.entrypoint","msg":"starting manager"}
{"level":"info","ts":"2025-05-08T18:14:04Z","msg":"Starting EventSource","controller":"amdgpu-node-labeller","source":"kind source: *v1.Node"}
{"level":"info","ts":"2025-05-08T18:14:04Z","msg":"Starting Controller","controller":"amdgpu-node-labeller"}
{"level":"info","ts":"2025-05-08T18:14:04Z","msg":"Starting workers","controller":"amdgpu-node-labeller","worker count":1}
```

> 4. It will be also helpful to see the node label from `kubectl get node <your worker node name> -oyaml | grep amd.com`

```
$ kubectl get node enc1-gpuvm015 -o yaml | grep amd\.com
    amd.com/gpu: "1"
    amd.com/gpu: "1"
```

**Comment by yansun1996** [comment]
@xiongzubiao thanks, that's a good point, I will push a fix for the next release.

**Comment by yansun1996** [comment]
@xiongzubiao 
it is worth mentioning that today around the same time you post this issue, 
we just released v1.2.2 and introduced a fix for node label cleaning up issue similar to the issue you posted
can you try with v1.2.2 ? 

1.
```bash
helm repo update
helm upgrade amd-gpu-operator -n kube-amd-gpu rocm/gpu-operator-charts --version=v1.2.2 --debug
```
2. make sure to pick up the latest node labeller image
```yaml
spec:
  devicePlugin:
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest
    nodeLabellerImagePullPolicy: Always
```

**Comment by xiongzubiao** [comment]
@yansun1996 No, v1.2.2 with `nodeLabellerImagePullPolicy: Always` doesn't fix it.

**Comment by yansun1996** [comment]
@xiongzubiao  I've reproduced the issue and the root cause has been confirmed, a fix is on the way https://github.com/ROCm/gpu-operator/pull/187 

thanks for pointing this out

**Comment by yansun1996** [comment]
Hi @xiongzubiao  we've patched a fix for the issue you mentioned. Please re-pull the v1.2.2 controller manager image, basically the image SHA256 would be 

```bash
$ kubectl get pod -n kube-amd-gpu amd-gpu-operator-gpu-operator-charts-controller-manager-56l6hj2 -oyaml | grep image
    image: docker.io/rocm/gpu-operator:v1.2.2
    imagePullPolicy: Always
    image: docker.io/rocm/gpu-operator:v1.2.2
    imageID: docker.io/rocm/gpu-operator@sha256:fffa03dc40f0358b6efe4fd82b4eb28566052f4f2a248c3a7edecc99d7a686ce
```
you can re-pull the image by setting pull policy to always and restart the controller manager pod.

We've verified on our side, let us know whether it works on your side or not with your ```DeviceConfig```.

**Comment by xiongzubiao** [comment]
@yansun1996 I can confirm it works now. Thanks for the quick fix!

**Comment by yansun1996** [comment]
thanks @xiongzubiao let me know if you have any more questions or suggestions !
